# MySQL.  Versions 4.1 and 5.0 are recommended.
#
# Install the MySQL driver:
#   gem install mysql
# On Mac OS X:
#   sudo gem install mysql -- --with-mysql-dir=/usr/local/mysql
# On Mac OS X Leopard:
#   sudo env ARCHFLAGS="-arch i386" gem install mysql -- --with-mysql-config=/usr/local/mysql/bin/mysql_config
#       This sets the ARCHFLAGS environment variable to your native architecture
# On Windows:
#   gem install mysql
#       Choose the win32 build.
#       Install MySQL and put its /bin directory on your path.
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
development: &defaults
  adapter: mysql
  encoding: utf8
  database: content_reporting
  username: root
  password: i8ylwjg4D6
  host: 127.0.0.1

cdx_enrollment:
  <<: *defaults
  database: cdxenroldb_v4

cdx_moodle:
  <<: *defaults
  database: moodle_master2

cdx_content:
  <<: *defaults
  database: content_50

cdx_content_41:
  <<: *defaults
  database: content_db
